<?php
//  Copyright CWSPS154. All rights reserved.
use CWSPS154\SalesOrderReports\Block\Adminhtml\Report\PendingOrderReportGrid;
use CWSPS154\SalesOrderReports\Model\Report\AbstractDashboardOrder;

/** @var PendingOrderReportGrid $this */
$pendingOrders = $this->getOrderDetails();
?>
<style>
    .admin__data-grid-wrap {
        margin-bottom: 2rem;
        max-width: 100%;
        padding-bottom: 1rem;
        padding-top: 2rem;
        page-break-inside: avoid;
    }

    .data-grid {
        border: none;
        font-size: 1.3rem;
        margin-bottom: 0;
        width: 100%;
        border-collapse: collapse;
    }

    table {
        background-color: transparent;
        color: #303030;
        width: 100%;
        border-collapse: collapse;
    }

    .data-grid th:first-child {
        border-left-color: #8a837f;
    }

    .data-grid .data-grid-th {
        background-clip: padding-box;
        color: #ffffff;
        padding: 1rem;
        position: relative;
        vertical-align: middle;
        text-align: left;
    }

    .data-grid th {
        background-color: #514943;
        border: 0.1rem dotted #8a837f;
        border-left-color: transparent;
        color: #ffffff;
        font-weight: 600;
        padding: 0.5rem;
        text-align: left;
    }

    .data-grid td {
        border: 0.1rem dotted #8a837f;
        padding: 0.5rem;
        text-align: left;
    }

    .data-grid th,
    .data-grid td {
        font-size: 1.3rem;
        line-height: 1.36;
        transition: background-color 0.1s linear;
        vertical-align: middle;
    }

    .data-rows:nth-child(even) {
        background-color: #f9f9f9;
    }

    .data-rows:nth-child(odd) {
        background-color: #ffffff;
    }

    .data-rows th, .data-rows td {
        text-align: center;
    }

    tr._odd-row {
        background-color: #f9f9f9;
    }
    .data-row .center {
        border: 0.1rem dotted #8a837f;
        padding: 0.5rem;
        text-align: center;
        vertical-align: middle;
    }
</style>
<div class="admin__data-grid-wrap" data-role="grid-wrapper">
    <table class="data-grid data-grid-draggable" data-role="grid">
        <thead>
        <tr class="data-row">
            <th class="data-grid-th center" colspan="12">
                <?= /* @noEscape */ __('Pending Order Report') ?>
            </th>
        </tr>
        <tr>
            <th class="data-grid-th" rowspan="2"><?= /* @noEscape */
                __('Ageing') ?></th>
            <?php foreach (array_keys(AbstractDashboardOrder::TYPES) as $type) { ?>
            <th class="data-grid-th" colspan="2"><?= /* @noEscape */
                __($type) ?></th>
            <?php } ?>
            <th class="data-grid-th" rowspan="2"><?= /* @noEscape */
                __('Total Order') ?></th>
            <th class="data-grid-th" rowspan="2"><?= /* @noEscape */
                __('Total Value') ?></th>
        </tr>
        <tr>
            <th class="data-grid-th"><?= /* @noEscape */
                __('No of orders') ?></th>
            <th class="data-grid-th"><?= /* @noEscape */
                __('Value') ?></th>
            <th class="data-grid-th"><?= /* @noEscape */
                __('No of orders') ?></th>
            <th class="data-grid-th"><?= /* @noEscape */
                __('Value') ?></th>
            <th class="data-grid-th"><?= /* @noEscape */
                __('No of orders') ?></th>
            <th class="data-grid-th"><?= /* @noEscape */
                __('Value') ?></th>
            <th class="data-grid-th"><?= /* @noEscape */
                __('No of orders') ?></th>
            <th class="data-grid-th"><?= /* @noEscape */
                __('Value') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php $grandTotals = [];
        $grandTotalSum = 0;
        $grandTotalOrder = 0; ?>
        <?php if (!empty($pendingOrders)) {
            $i = 0;
            foreach ($pendingOrders as $key => $order) { $i++;?>
                <tr class="data-row <?php if($i%2 == 0) { echo '_odd-row';} ?>">
                    <td><?= /* @noEscape */
                        $key ?></td>
                    <?php $totalNoOfOrders = 0;
                    $totalValue = 0;
                    $totalOrder = 0;?>
                    <?php foreach ($order as $orderItem) { ?>
                        <?php
                        $type = $orderItem->getType();
                        $noOfOrders = $orderItem->getNoOfOrders();
                        $value = $orderItem->getValue();
                        if (!isset($grandTotals[$type])) {
                            $grandTotals[$type]['no_of_orders'] = 0;
                            $grandTotals[$type]['value'] = 0;
                        }
                        $grandTotals[$type]['no_of_orders'] += $noOfOrders;
                        $grandTotals[$type]['value'] += $value;

                        $totalNoOfOrders += $noOfOrders;
                        $totalValue += $value;
                        $totalOrder += $noOfOrders;
                        ?>
                        <td><?= /* @noEscape */
                            $noOfOrders ?></td>
                        <td><?= /* @noEscape */
                            $this->getFormattedPriceByStore($value) ?></td>
                    <?php } ?>
                    <td><?= /* @noEscape */
                        $totalOrder ?></td>
                    <?php $grandTotalOrder += $totalOrder; ?>
                    <td><?= /* @noEscape */
                        $this->getFormattedPriceByStore($totalValue) ?></td>
                    <?php $grandTotalSum += $totalValue; ?>
                </tr>
            <?php } ?>
            <tr class="data-row">
                <th class="data-grid-th"><?= /* @noEscape */
                    __('Grand Total') ?></th>
                <?php foreach ($grandTotals as $grandTotal) { ?>
                    <th class="data-grid-th"><?= /* @noEscape */
                        $grandTotal['no_of_orders']; ?></th>
                    <th class="data-grid-th"><?= /* @noEscape */
                        $this->getFormattedPriceByStore($grandTotal['value']); ?></th>
                <?php } ?>
                <th class="data-grid-th"><?= /* @noEscape */
                    $grandTotalOrder ?></th>
                <th class="data-grid-th"><?= /* @noEscape */
                    $this->getFormattedPriceByStore($grandTotalSum) ?></th>
            </tr>
        <?php } else { ?>
            <tr class="data-row">
                <td colspan="12" class="center"><?= /* @noEscape */
                    __('Please switch the scope to store base view') ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>




